const eng = [
  "ONE",
  "In which the links of coincidence are forged into the chain of fate",
  "The morning train from St. Petersburg, still enveloped in the swirling smoke from its locomotive, had scarcely slowed to a halt at the platform of Nikolaevsky Station, and the conductors had only just unfolded the short flights of steps and tipped their peaked caps in salute, when a young man attired in quite remarkable style leapt out of one of the first-class carriages",
  "He seemed to have sprung straight out of some picture in a Parisian magazine devoted to the glories of the 1882 summer-season fashion: a light suit of sandy-colored wild silk, a wide- brimmed hat of Italian straw, shoes with pointed toes, white spats with silver press-studs, and in his hand an elegant walking cane with a knob that was also silver",
  "However, it was not so much the passenger’s foppish attire that attracted attention as his physique, which was quite imposing, one might almost say spectacular",
  "The young man was tall, with a trim figure and wide shoulders",
  "He regarded the world through clear blue eyes, and his slim mustache with curled ends sat quite extraordinarily well with his regular features, which included one distinctive peculiarity — the neatly combed black hair shaded intriguingly into silver-gray at the temples",
  "The porters made short work of unloading the young man’s luggage, which is itself worthy of special mention",
  "In addition to suitcases and traveling bags, they carried out onto the platform a folding tricycle, a set of gymnastic weights, and bundles of books in various languages",
  "Last of all there emerged from the carriage a short, bandy-legged oriental gentleman with a compact physique and an extremely solemn face and fat cheeks",
  "He was dressed in green livery, combined discordantly with wooden sandals and a gaudy paper fan hanging around his neck on a silk string",
  "This squat individual was clutching a quadrangular lacquered box in which was growing a tiny pine tree, looking for all the world as though it had been transported to the Moscow railway station from the kingdom of Lilliput",
  "Running his eye over the distinctly uninspiring structures of the railway terminus with a curious air of excitement, the young man inhaled the sooty station air and whispered: “My God, six long years.” However, he was not permitted to indulge his reverie for long",
  "The passengers from the St. Petersburg train were already being waylaid by cabbies, most of whom were attached to Moscow’s various hotels",
  "Battle was joined for the handsome dark-haired gentleman, who appeared to be a most desirable client, by knights of the road from the four hotels regarded as the most chic in Russia’s old capital — the Metropole, the Loskutnaya, the Dresden, and the Dusseaux",
  "“Come stay at the Metropole, sir!” the first cabbie exclaimed",
  "“An absolutely modern hotel in the genuine European style! And the suite has a special box room for your Chinee here!”",
  "“He is not Chinese, but J-Japanese,” the young man explained, incidentally revealing that he spoke with a slight stammer",
  "“And I would prefer him to lodge with me.”",
  "“Then Your Honor should come to us at the Loskutnaya,” said the next cabbie, shouldering his competitor aside",
  "“If you take a suite for five rubles or more, we drive you for free",
  "I’ll get you there quick as a wink!”",
  "“I stayed in the Loskutnaya once,” the young man declared",
  "“It’s a good hotel.”"
];