const pl = [
"JEDEN",
  "W którym łańcuchy zbiegów okoliczności zostają wykute w łańcuch przeznaczenia",
  "Poranny pociąg z Petersburga, wciąż spowity kłębami dymu ze swojej lokomotywy, ledwie zwolnił na peronie Dworca Nikołajewskiego, a konduktorzy dopiero co rozstawili krótkie drabinki i zdjęli czapki na powitanie, gdy młody człowiek w niezwykle osobliwym stroju wyskoczył z jednego z wagonów pierwszej klasy",
  "Wyglądał, jakby wyszedł prosto z jakiejś ilustracji w paryskim czasopiśmie poświęconym chwale letniej mody roku 1882: lekki garnitur z piaskowego dzikiego jedwabiu, szerokokapeluszowy włoski kapelusz słomkowy, buty ze spiczastymi noskami, białe getry ze srebrnymi guzikami, a w rękach elegancka laska ze srebrną rękojeścią",
  "Jednak uwagę przyciągał nie tyle fantazyjny strój pasażera, ile jego budowa ciała, która była bardzo imponująca, można wręcz powiedzieć — efektowna",
  "Młody człowiek był wysoki, o wysportowanej sylwetce i szerokich ramionach",
  "Patrzył na świat jasnymi niebieskimi oczami, a jego cienkie wąsy z podkręconymi końcami zadziwiająco harmonizowały z regularnymi rysami twarzy, wśród których była jedna charakterystyczna cecha — starannie ułożone czarne włosy, intrygująco przechodzące w srebrzystoszare na skroniach",
  "Tragarze szybko uporali się z rozładunkiem bagażu młodego człowieka, który sam w sobie zasługuje na osobną wzmiankę",
  "Oprócz walizek i toreb podróżnych wynieśli na peron składany trójkołowy rower, zestaw ciężarków gimnastycznych oraz wiązki książek w różnych językach",
  "Jako ostatni z wagonu wyszedł niski, koślawy wschodni jegomość o zwartej budowie ciała, z niezwykle poważną twarzą i pełnymi policzkami",
  "Ubrany był w zieloną liberie, pozostającą w dysonansie z drewnianymi sandałami i jaskrawym papierowym wachlarzem na jedwabnym sznurku zawieszonym na szyi",
  "Ten krępy człowiek trzymał kwadratowe lakierowane pudełko, w którym rosła mała sosna, jakby przeniesiona na Dworzec Moskiewski z królestwa Liliputów",
  "Obrzucając spojrzeniem raczej nieimponujące zabudowania terminalu kolejowego z ciekawym uczuciem podniecenia, młody człowiek wciągnął zadymione powietrze stacji i wyszeptał: „Boże mój, sześć długich lat”. Jednak nie pozwolono mu długo oddawać się wspomnieniom",
  "Pasażerów petersburskiego pociągu już otoczyli dorożkarze, z których większość była przypisana do różnych moskiewskich hoteli",
  "Bitwę o atrakcyjnego ciemnowłosego jegomościa, który wydawał się niezwykle pożądanym klientem, stoczyli woźnice z czterech hoteli uważanych za najbardziej szykowne w starej stolicy Rosji — „Metropol”, „Łoskutnaja”, „Drezden” i „Dussot”",
  "„Zatrzymaj się w Metropolu, sir!” — zawołał pierwszy dorożkarz",
  "„Całkowicie nowoczesny hotel w prawdziwym europejskim stylu! A w apartamencie jest osobny pokój dla pańskiego Chińczyka!”",
  "„On nie jest Chińczykiem, tylko ja-Japończykiem”, — wyjaśnił młody człowiek, ujawniając przy okazji lekkie jąkanie",
  "„I wolałbym, żeby mieszkał ze mną.”",
  "„W takim razie Wasza Ekscelencja powinna przyjechać do nas, do Łoskutnej”, — powiedział następny dorożkarz, odpychając konkurenta",
  "„Jeśli weźmie pan apartament za pięć rubli lub więcej, zawieziemy pana za darmo",
  "Dostarczymy pana natychmiast!”",
  "„Raz już zatrzymałem się w Łoskutnej”, — oznajmił młody człowiek",
  "„Dobry hotel.”"
];